<a href="https://colab.research.google.com/github/jyothiradithya123/Sirpi-practice-qns/blob/main/Week_3_Solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd

In [ ]:
automobile = pd.read_csv('/content/drive/MyDrive/data/Automobile.csv')
automobile.head()



symboling  normalized_losses         make fuel_type aspiration  \
0          3                168  alfa-romero       gas        std   
1          3                168  alfa-romero       gas        std   
2          1                168  alfa-romero       gas        std   
3          2                164         audi       gas        std   
4          2                164         audi       gas        std   

  number_of_doors   body_style drive_wheels engine_location  wheel_base  ...  \
0             two  convertible          rwd           front        88.6  ...   
1             two  convertible          rwd           front        88.6  ...   
2             two    hatchback          rwd           front        94.5  ...   
3            four        sedan          fwd           front        99.8  ...   
4            four        sedan          4wd           front        99.4  ...   

   engine_size  fuel_system  bore  stroke compression_ratio horsepower  \
0          130         mpfi  3.47    2.68               9.0        111   
1          130         mpfi  3.47    2.68               9.0        111   
2          152         mpfi  2.68    3.47               9.0        154   
3          109         mpfi  3.19    3.40              10.0        102   
4          136         mpfi  3.19    3.40               8.0        115   

   peak_rpm city_mpg  highway_mpg  price  
0      5000       21           27  13495  
1      5000       21           27  16500  
2      5000       19           26  16500  
3      5500       24           30  13950  
4      5500       18           22  17450  

[5 rows x 26 columns]

In [ ]:
# 1. Loading a CSV File & Basic Exploration
# Given a CSV file named "Automobile.csv":
# Task
# Write Python code to:
# •	Load the CSV file into a Pandas DataFrame.
# •	Display the first 30 rows.
# •	Print column names.
# •	Print No of Rows & Columns
# •	Find the Data Types of every column & check if there are any mismatch
# •	What are the minimum & maximum price of the car & state fuel type they belong to
# •	List all the unique engine types
# •	Find the horsepower range
# •	What is the average mpg in cities & highway. Which is better?
# •	What are the different Automobile makes present & which has maximum count?
# ________________________________________
import pandas as pd

# automobile = pd.read_csv('/Automobile.csv')
# automobile
automobile_df = pd.DataFrame(automobile)
automobile_df.head(30)
automobile_df.columns
automobile_df.shape
automobile_df.info()
automobile_df['price'].max()
automobile_df['engine_type'].unique()
horsepower_range = automobile_df['horsepower'].max() - automobile_df['horsepower'].min()
horsepower_range
city_mpg_avg = automobile_df['city_mpg'].mean()
highway_mpg_avg = automobile_df['highway_mpg'].mean()
if(city_mpg_avg > highway_mpg_avg):
  print('city_mpg_avg is greater and its better')
else:
  print('highway_mpg is greater and its better')

# automobile_df

automobile_df['make'].value_counts()
automobile_df['make'].value_counts().max()



# automobile.tail()
# automobile.describe()
# automobile.info()
# automobile.shape


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   symboling            201 non-null    int64  
 1   normalized_losses    201 non-null    int64  
 2   make                 201 non-null    object 
 3   fuel_type            201 non-null    object 
 4   aspiration           201 non-null    object 
 5   number_of_doors      201 non-null    object 
 6   body_style           201 non-null    object 
 7   drive_wheels         201 non-null    object 
 8   engine_location      201 non-null    object 
 9   wheel_base           201 non-null    float64
 10  length               201 non-null    float64
 11  width                201 non-null    float64
 12  height               201 non-null    float64
 13  curb_weight          201 non-null    int64  
 14  engine_type          201 non-null    object 
 15  number_of_cylinders  201 non-null    obj

32

In [ ]:
# 2. Accessing Data with .loc[]
# Using the following DataFrame:
# df = pd.DataFrame({
#     "Name": ["Alice", "Bob", "Charlie", "David"],
#     "Age": [24, 27, 22, 32],
#     "Score": [85, 90, 78, 88]
# })
# Task
# •	Retrieve the row where Name == "Charlie" using .loc[].
# •	Select only the Age and Score columns for "Alice" and "Bob" using .loc[].
# ________________________________________

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [24, 27, 22, 32],
    "Score": [85, 90, 78, 88]
})

df[df['Name'] == 'Charlie']
df.loc[df['Name'] == 'Charlie']

df.loc[(df['Name'] == 'Alice') |(df['Name'] == 'Bob')]


Name  Age  Score
0  Alice   24     85
1    Bob   27     90

In [ ]:
# 3. Accessing Data with .iloc[]
# Using the same DataFrame from Question 2, write code to:
# •	Retrieve the second row using .iloc[].
# •	Extract the last two rows using .iloc[].
# ________________________________________
df.iloc[1]
df.iloc[[2,3]]

Name  Age  Score
2  Charlie   22     78
3    David   32     88

In [ ]:
# 4. Filtering Rows Based on Conditions
# Using the following DataFrame:
# df = pd.DataFrame({
#     "Employee": ["John", "Alice", "Bob", "David"],
#     "Salary": [50000, 60000, 55000, 65000],
#     "Department": ["IT", "HR", "IT", "Finance"]
# })
# Task
# Write a Pandas command to:
# •	Select only IT employees.
# •	Select employees with a salary greater than 55,000.
# ________________________________________
df = pd.DataFrame({
    "Employee": ["John", "Alice", "Bob", "David"],
    "Salary": [50000, 60000, 55000, 65000],
    "Department": ["IT", "HR", "IT", "Finance"]
})
df[df['Department'] == 'IT']
df.loc[df['Salary'] > 55000]

Employee  Salary Department
1    Alice   60000         HR
3    David   65000    Finance

In [ ]:
# 5. Applying Functions to a Column
# Using the following DataFrame:
# df = pd.DataFrame({
#     "Student": ["A", "B", "C", "D"],
#     "Marks": [45, 78, 62, 90]
# })
# Task
# Write a function that:
# •	Converts marks below 50 to "Fail", and 50 or above to "Pass".
# •	Apply this function to the "Marks" column and create a new column "Result".
# ________________________________________
df = pd.DataFrame({
    "Student": ["A", "B", "C", "D"],
    "Marks": [45, 78, 62, 90]
})

def results(marks):
  return "Pass" if marks >= 50 else "Fail"

df['Result'] = df['Marks'].apply(results)
df

Student  Marks Result
0       A     45   Fail
1       B     78   Pass
2       C     62   Pass
3       D     90   Pass

In [ ]:
# 6. NumPy - Creating and Reshaping Arrays
# Write Python code to:
# •	Create a NumPy array with values from 1 to 12.
# •	Reshape it into a 3x4 matrix.
# ________________________________________
import numpy as np

nums = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

nums_matrix = nums.reshape(3,4)
nums_matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# 7. NumPy - Broadcasting & Element-wise Operations
# You are given the following NumPy arrays:
# a = np.array([1, 2, 3])
# b = np.array([10, 20, 30])
# Task
# Perform:
# 1.	Element-wise multiplication of a and b.
# 2.	Add 5 to each element of a using broadcasting.
# ________________________________________
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

c = np.multiply(a,b)
c

a+5
b+5

array([15, 25, 35])

In [ ]:

# 8. Finding Maximum and Minimum Values in a NumPy Array
# Given:
# arr = np.array([[3, 7, 2], [4, 9, 6]])
# Task
# •	Find the maximum value in the entire array.
# •	Find the minimum value in each row.
# ________________________________________
arr = np.array([[3, 7, 2], [4, 9, 6]])
arr

arr.max(),arr.min()

(9, 2)

In [ ]:

# 9. Grouping & Aggregation in Pandas
# You have the following DataFrame:
# df = pd.DataFrame({
#     "Department": ["IT", "HR", "IT", "Finance", "HR"],
#     "Salary": [70000, 50000, 80000, 60000, 52000]
# })
# Task
# Write a Pandas command to:
# •	Group the DataFrame by "Department" and calculate the average salary per department.
# ________________________________________
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [70000, 50000, 80000, 60000, 52000]
})
df.groupby('Department').mean()


Salary
Department         
Finance     60000.0
HR          51000.0
IT          75000.0

In [ ]:
# 10. Sorting a DataFrame
# Given the following DataFrame:
# df = pd.DataFrame({
#     "City": ["New York", "Los Angeles", "Chicago", "Houston"],
#     "Population": [8419600, 3980400, 2716000, 2328000]
# })
# Task
# •	Sort the DataFrame by Population in descending order.
# ________________________________________
df = pd.DataFrame({
    "City": ["New York", "Los Angeles", "Chicago", "Houston"],
    "Population": [8419600, 3980400, 2716000, 2328000]
})
df.sort_values(by = "Population",ascending=False)

City  Population
0     New York     8419600
1  Los Angeles     3980400
2      Chicago     2716000
3      Houston     2328000

In [ ]:

# 11. Multi-Indexing in Pandas
# You are given the following DataFrame:
# data = {
#     "Region": ["North", "North", "South", "South", "East", "East"],
#     "City": ["A", "B", "A", "B", "A", "B"],
#     "Sales": [200, 150, 180, 220, 300, 250]
# }
# df = pd.DataFrame(data).set_index(["Region", "City"])
# Task
# •	Retrieve the sales value for City A in the South Region using multi-indexing.
# ________________________________________
data = {
    "Region": ["North", "North", "South", "South", "East", "East"],
    "City": ["A", "B", "A", "B", "A", "B"],
    "Sales": [200, 150, 180, 220, 300, 250]
}
df = pd.DataFrame(data).set_index(["Region", "City"])
sales_value = df.loc[("South", "A"), "Sales"]
sales_value


180

In [ ]:

# 12. Creating a DataFrame from a NumPy Array
# Generate a 5x4 NumPy array with random integers between 10 and 99 and convert it into a Pandas DataFrame with column names ["A", "B", "C", "D"].
# ________________________________________
random_matrix = np.random.randint(10,99,size = (5,4))
random_matrix

df = pd.DataFrame(random_matrix,columns = ["A","B","C","D"])
df

A   B   C   D
0  79  57  90  56
1  61  75  34  80
2  38  93  92  44
3  42  64  51  91
4  78  62  95  35

In [ ]:
# 13. Conditional Column Update
# Given the following DataFrame:
# df = pd.DataFrame({
#     "Student": ["Alice", "Bob", "Charlie", "David"],
#     "Marks": [88, 45, 76, 90],
#     "Attendance": [85, 50, 90, 60]
# })
# Task
# Write a one-liner Pandas command to set "Marks" to 0 for students whose "Attendance" is less than 60.
# ________________________________________
df = pd.DataFrame({
    "Student": ["Alice", "Bob", "Charlie", "David"],
    "Marks": [88, 45, 76, 90],
    "Attendance": [85, 50, 90, 60]
})
df.loc[df["Attendance"] < 60,"Marks"] = 0
df

Student  Marks  Attendance
0    Alice     88          85
1      Bob      0          50
2  Charlie     76          90
3    David     90          60

In [ ]:
# 14. Advanced Filtering
# From a CSV file "employees.csv" with columns:
# EmployeeID, Department, Salary, Experience (in years).
# Note: You should create “employees.csv” & perform the below task
# Task
# Write a Pandas query to:
# •	Select employees from "IT" or "Finance" department
# •	Having Salary > 60,000
# •	AND at least 5 years of experience
# ________________________________________
data = {
    "EmployeeID": [1, 2, 3, 4, 5],
    "Department": ["IT", "Finance", "HR", "IT", "Finance"],
    "Salary": [70000, 80000, 55000, 65000, 75000],
    "Experience": [6, 7, 3, 5, 8]
}

df = pd.DataFrame(data)
df.to_csv("employees.csv", index=False)
df = pd.read_csv('employees.csv')

new_df =  df.query('Department in ["IT", "Finance"] and Salary > 60000 and Experience >= 5')
new_df

EmployeeID Department  Salary  Experience
0           1         IT   70000           6
1           2    Finance   80000           7
3           4         IT   65000           5
4           5    Finance   75000           8

In [ ]:

# 15. Grouping & Aggregation with Multiple Conditions
# Given the following DataFrame:
# df = pd.DataFrame({
#     "Department": ["IT", "HR", "IT", "Finance", "HR", "Finance", "IT"],
#     "Salary": [70000, 50000, 80000, 60000, 52000, 72000, 65000],
#     "Experience": [5, 4, 7, 3, 2, 8, 6]
# })
# Task
# Find the average salary for each department, but only for employees with at least 5 years of experience.
# ________________________________________

df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR", "Finance", "IT"],
    "Salary": [70000, 50000, 80000, 60000, 52000, 72000, 65000],
    "Experience": [5, 4, 7, 3, 2, 8, 6]
})

experience = df[df["Experience"] > 5]
avg_salary = experience.groupby("Department")["Salary"].mean()
avg_salary

Department
Finance    72000.0
IT         72500.0
Name: Salary, dtype: float64

In [ ]:
# 16. NumPy - Complex Indexing
# Create a 5x5 NumPy array with random values between 1 and 100.
# Write a NumPy command to:
# •	Extract only even numbers from the array.
# •	Extract values from the last row and last column.
# •	Replace all values greater than 50 with 0.
# ________________________________________

arr = np.random.randint(1,101,size = (5,5))
even_nums = arr[arr % 2 == 0]
even_nums
last_row = arr[-1:,:]
last_row
last_col = arr[:,-1]
last_col

arr[arr > 50] = 0
arr



array([[11, 12, 24,  0,  0],
       [ 0,  0, 34,  0,  0],
       [44, 16, 16, 33, 30],
       [17, 20,  0, 29,  0],
       [10,  0, 34, 29,  0]])

In [ ]:
# 17. Matrix Multiplication
# Given the two NumPy matrices:
# A = np.array([[2, 4], [6, 8]])
# B = np.array([[1, 3], [5, 7]])
# Task
# Perform matrix multiplication and output the result.
# ________________________________________
A = np.array([[2, 4], [6, 8]])
B = np.array([[1, 3], [5, 7]])

C = np.dot(A,B)
C

array([[22, 34],
       [46, 74]])

In [ ]:
# 18. Finding Unique & Common Elements
# You are given two NumPy arrays:
# arr1 = np.array([10, 20, 30, 40, 50, 60])
# arr2 = np.array([30, 40, 70, 80, 90])
# Task
# •	Find the elements that are common in both arrays.
# •	Find the elements that are only present in arr1 but not in arr2.
# ________________________________________
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([30, 40, 70, 80, 90])

common = np.intersect1d(arr1,arr2)
common

unique = np.setdiff1d(arr1,arr2)
unique


array([10, 20, 50, 60])

In [ ]:
# 19. Sorting & Ranking in Pandas
# You are given the following DataFrame:
# df = pd.DataFrame({
#     "Player": ["A", "B", "C", "D"],
#     "Score": [200, 450, 300, 150]
# })
# Task
# •	Sort the players by descending Score.
# •	Assign ranking to each player (1st, 2nd, 3rd...) without skipping numbers.
# ________________________________________
df = pd.DataFrame({
    "Player": ["A", "B", "C", "D"],
    "Score": [200, 450, 300, 150]
})
sorted_df = df.sort_values(by = "Score",ascending = False)
sorted_df

sorted_df['Rank'] = sorted_df['Score'].rank(ascending=False,method = 'dense')
sorted_df

Player  Score  Rank
1      B    450   1.0
2      C    300   2.0
0      A    200   3.0
3      D    150   4.0

In [ ]:
# 20. Optimizing Pandas Performance
# You have a large CSV file ("big_data.csv") with 1 million rows.
# Note: You should search & download a large csv file from any portal & use it to perform below tasks
# Task
# Write optimized Pandas code to:
# •	Load only specific columns: "CustomerID" and "PurchaseAmount".
# •	Load only the first 100,000 rows.
# •	Use an efficient data type for "CustomerID" to save memory.


import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/data/shopping_trends.csv')
df = df.rename(columns = {'Customer ID':'CustomerID','Purchase Amount (USD)':'PurchaseAmount'})
df.head(100)
df.info()




<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   CustomerID                3900 non-null   int64  
 1   Age                       3900 non-null   int64  
 2   Gender                    3900 non-null   object 
 3   Item Purchased            3900 non-null   object 
 4   Category                  3900 non-null   object 
 5   PurchaseAmount            3900 non-null   int64  
 6   Location                  3900 non-null   object 
 7   Size                      3900 non-null   object 
 8   Color                     3900 non-null   object 
 9   Season                    3900 non-null   object 
 10  Review Rating             3900 non-null   float64
 11  Subscription Status       3900 non-null   object 
 12  Payment Method            3900 non-null   object 
 13  Shipping Type             3900 non-null   object 
 14  Discount